# Use root/example as user/password credentials
version: '3'

services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
